### ISSUE TITLE
install help 2

### ISSUE THREAD

**Issue by Edcaaaa4gy53** [Mee12345/GMod-Seamless-Portals#28]
Bruh i did everything installed and added folder and zip called seamless_portals to the garrys mod addons folder, still not appearing in addons menu HELP

**Comment by WasabiThumb** [comment]
You added a zip to the addons folder? That wasn't in the instructions...

Also, it may not show up in the ingame addons list since it's not a GMA, but the Seamless Portals categories should still show up in the Entities/Weapons categories if it is installed which is generally your main way of interfacing with the addon right now.

**Comment by WasabiThumb** [comment]
And of course Mee said that it will be on the workshop in about 2 days if you want to wait for that. I'm considering releasing my rejected portal funneling feature as a separate addon on the workshop too if you want to look for that ;)

**Comment by Mee12345** [comment]
its on workshop so, just use that
